---
title: "index"
author: "Jennifer Bone, Jennifer Kidson, Julia Paltseva"
date: "January 27, 2016"
output: html_document
---

# Citizen Monitoring
________________________________________
## Types of data
Data collected will consist of text survey responses. Information will include phone numbers, timestamp, location information, demographic information, and a survey response, which may be numeric or text. 

The data will be categorized according to which survey question it is answering. This will be done with the timestamp data that comes in with each survey response. Once responses are separated into the proper questions, summary statistics will be generated for each one.
 
## Data and metadata standards
Metadata will include explanations of each of the following category headings: nominated, zone, years_zone, gender, age, and satisfaction.
 
## Policies for access and sharing
Since some versions of this data are tied to specific survey respondents (via telephone number) it should not be shared in a raw format. Statistics generated from the data may be shared in accordance with PI's instructions.

## Policies and provisions for re-use, re-distribution
To be specified by PI.

## Plans for archiving and preservation of access
To be specified by PI.